name: Build package

on: [ push, pull_request, workflow_dispatch ]

# written referencing apollo save tool psp's CI

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

      # install latest pspdev sdk
    - name: Install mingw
      run: |
        sudo apt update
        sudo apt install -y g++-mingw-w64-i686

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Build asi
      run: |
        bash build.sh

    - name: Fetch ThirteenAG's asi loader
      run: |
        wget https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/v7.7.0/Ultimate-ASI-Loader.zip
        unzip Ultimate-ASI-Loader.zip
        mv dinput8.dll version.dll

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: project_torque_ffb_hotpatch_${{ env.sha_name }}
        path: |
           project_torque_ffb_hotpatch.asi
           project_torque_ffb_hotpatch_reversed.asi
           version.dll
           global.ini
        if-no-files-found: error
